### ISSUE TITLE
Collections flag not work

### ISSUE THREAD

**Issue by mitay-walle** [GieziJo/ScriptableObjectVariant#14]
I've List of references to another ScriptableObjects, and IsOverriden is true, but if I turn it off, I can't turn it on back

**Comment by GieziJo** [comment]
Thanks for the bug report. Could you write a minimal working example of what is not working?
This code works as expected for me:
```csharp
[SOVariant, CreateAssetMenu]
public class TestSO : ScriptableObject
{
    public List<TestSONonVariant> myList;
}
```
```csharp
[CreateAssetMenu]
public class TestSONonVariant : ScriptableObject
{
    [SerializeField] private float data;
}
```
