### ISSUE TITLE
Inspector inefficiently use space

### ISSUE THREAD

**Issue by mitay-walle** [GieziJo/ScriptableObjectVariant#16]
In factm you dont need original values. Your header + small flag eat 50% of space. Also you even not need a flag, Blue line with Unity prefab override system take a little space and works as intended.

**Comment by GieziJo** [comment]
This is a design choice. I prefer to have all the information visible at all time since it is meant to contain data, so I won't change this.
But feel free to implement this in your way, maybe we could have an option to toggle between modes?
